### ISSUE TITLE
Randomizer unsupported rom

### ISSUE THREAD

**Issue by 77JDub77** [Dabomstew/pokecrystal-speedchoice-legacy#15]
I am currently having issues figuring out how to randomize pokecrystal speedchoice. I am using the newest version of the universal randomizer and it keeps saying that it is an unsupported rom. Any help would be appreciated,

**Comment by Dabomstew** [comment]
Late comment but speedchoice requires https://github.com/Dabomstew/universal-pokemon-randomizer/tree/speedchoice-support rando
